###
POST http://localhost:8080/api/reservation
Content-Type: application/json

{
  "email": "test@test.com",
  "startDate": "2026-10-18T12:00",
  "endDate": "2026-10-18T14:00",
  "registrationNumber": "CBY12345",
  "parkingSpotId": "U145",
  "cardNumber": "123-456-789",
  "cvv": 100
}

###
GET http://localhost:8080/api/reservation/87eef43b-28a1-4473-b7f2-16499b5cf7a9





