###
POST http://localhost:8080/api/reservation
Content-Type: application/json

{
  "email": "test@test.com",
  "startDate": "2026-10-18T12:00",
  "endDate": "2026-10-18T14:00",
  "registrationNumber": "CBY12345",
  "parkingSpotId": "U145",
  "cardNumber": "123-456-789",
  "cvv": 100
}

###
GET http://localhost:8080/api/reservation/cf55527c-9ef5-4c21-9b2a-da7ac3ddc759



